"""about author

Revision ID: 966044ab0d83
Revises: e11785468135
Create Date: 2024-06-25 16:20:02.550015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966044ab0d83'
down_revision = 'e11785468135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
